version: "3"
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./pukiwiki:/var/www/html/pukiwiki
            - ./contents:/var/www/html/contents
            - ./default.conf:/etc/nginx/conf.d/default.conf

    php:
        container_name: php
        image: php:8-fpm
        restart: always
        volumes:
            - ./pukiwiki:/var/www/html/pukiwiki
            - ./contents:/var/www/html/contents
