version: "3"
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./pukiwiki-1.5.4_utf8:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf

    php:
        container_name: php
        image: php:8-fpm
        volumes:
            - ./pukiwiki-1.5.4_utf8:/var/www/html
